
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Osman Karadeniz
 */
public class Fakulteislemleri extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst=null;
PreparedStatement pst2=null;
    /**
     * Creates new form Fakulteislemleri
     */
    public Fakulteislemleri() {
        initComponents();
        conn=javabaglanti.BaglantiDb();
        fakulte_getir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        geri = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fakulte = new javax.swing.JTextField();
        sil = new javax.swing.JButton();
        fakulte_sil = new javax.swing.JComboBox<>();
        ekle = new javax.swing.JButton();
        fakulte_guncelle = new javax.swing.JComboBox<>();
        yeni_fakulte = new javax.swing.JTextField();
        guncelle = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        hakkinda = new javax.swing.JMenu();
        hakkimizda = new javax.swing.JMenuItem();
        cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fırat Üniversitesi Kütüphane Otomasyonu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(155, 30, 72));

        geri.setBackground(new java.awt.Color(255, 255, 255));
        geri.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        geri.setText("<< Geri Dön");
        geri.setFocusable(false);
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FAKÜLTE ( EKLE / SİL / GÜNCELLE)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(geri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(geri)
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Yeni Fakülte Adı :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Fakülte Adı :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fakülte :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 60, 30));
        getContentPane().add(fakulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, 30));

        sil.setBackground(new java.awt.Color(255, 255, 255));
        sil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sil.setText(" SİL");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        getContentPane().add(sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 180, 30));

        getContentPane().add(fakulte_sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, 30));

        ekle.setBackground(new java.awt.Color(255, 255, 255));
        ekle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ekle.setText("EKLE");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });
        getContentPane().add(ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 180, 30));

        getContentPane().add(fakulte_guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 180, 30));
        getContentPane().add(yeni_fakulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 180, 30));

        guncelle.setBackground(new java.awt.Color(255, 255, 255));
        guncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guncelle.setText("GÜNCELLE");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 180, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fakülte :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, 30));

        hakkinda.setText("Sistem");
        hakkinda.setAutoscrolls(true);
        hakkinda.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hakkinda.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        hakkinda.setInheritsPopupMenu(true);

        hakkimizda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/bilgi.png"))); // NOI18N
        hakkimizda.setText("Proje Hakkında");
        hakkinda.add(hakkimizda);

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/cikis.png"))); // NOI18N
        cikis.setText("Çıkış Yap");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        hakkinda.add(cikis);

        jMenuBar1.add(hakkinda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(557, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      void fakulte_getir() {
        
        fakulte_sil.removeAllItems();
        fakulte_sil.addItem("Seç");
        fakulte_sil.setSelectedIndex(0);
        
        fakulte_guncelle.removeAllItems();
        fakulte_guncelle.addItem("Seç");
        fakulte_guncelle.setSelectedIndex(0);
        
        try {

            String sql = "select fakulte_adi from fakulteler";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                fakulte_sil.addItem(rs.getString("fakulte_adi"));
                fakulte_guncelle.addItem(rs.getString("fakulte_adi"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
    }
    
    
    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        setVisible(false);
        new Ogrenciislemleri().setVisible(true);
    }//GEN-LAST:event_geriActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        setVisible(false);

        Giris girisform = new Giris();
        girisform.setVisible(true);
    }//GEN-LAST:event_cikisActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed

        String fakulte_adi = (String) fakulte_sil.getSelectedItem();
        
        
        if(!fakulte_adi.equals("Seç"))
        {
        String sql="delete from fakulteler where fakulte_adi='"+fakulte_adi.trim()+"'";
        String sql2="DELETE FROM bolumler where fakulte_id IN (select fakulte_id from fakulteler where fakulte_adi='"+fakulte_adi.trim()+"')";
            String sql3="delete from ogrenciler where bolum_id in(select bolum_id from bolumler where fakulte_id in (select fakulte_id from fakulteler where fakulte_adi='"+fakulte_adi.trim()+"'))";
        
        try{

            int kontrol_0 =JOptionPane.showConfirmDialog(null,"DİKKAT ! -> SİLMEK ÜZERE OLDUĞUNUZ FAKÜLTE İLE BİRLİKTE\nFAKÜLTEYE AİT BÖLÜMLER VE ÖĞRENCİLERİ SİLİNECEKTİR !\nBu işleme devam etmek istiyormusunuz ?");
            int kontrol_1=-1;

            if(kontrol_0==0)
            {
                kontrol_1 = JOptionPane.showConfirmDialog(null,fakulte_adi+" Silmeyi Onaylıyorum");
            }

            if(kontrol_1==0)
            {
                
                //BAĞIMLI DEĞİŞKENLERDEN BAĞIMSIZA DOĞRU SİLEREK GİDİYORUZ.
                pst = conn.prepareStatement(sql3);
                pst.execute();
                pst.close();
                
                
                pst = conn.prepareStatement(sql2);
                pst.execute();
                pst.close();

                pst2 = conn.prepareStatement(sql);
                pst2.execute();
                pst2.close();

                JOptionPane.showMessageDialog(null, "SİLME İŞLEMİ BAŞARILI !");

                fakulte_getir();
            }
            else{
                JOptionPane.showMessageDialog(null, "Silme İşlemi İptal Edildi !");
            }

        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
            e.printStackTrace();
        }
        }
        else
        {
        JOptionPane.showConfirmDialog(null,"Lütfen bir fakülte seçiniz !");
        }
    }//GEN-LAST:event_silActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        try{

            String fakulte_adi = fakulte.getText().trim();

            String sql ="insert into fakulteler values (null,?)";
            String sql1 = "select * from fakulteler where fakulte_adi='"+fakulte_adi+"'";

            if(!(fakulte_adi.isBlank()))
            {
                pst=conn.prepareStatement(sql1);
                rs=pst.executeQuery();

                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null, "Fakülte Eklenemedi! -> Fakülte Zaten Mevcut. ");
                }
                else
                {
                    pst = conn.prepareStatement(sql);
                    pst.setString(1,fakulte_adi);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Fakülte Ekleme Başarılı !");
                    fakulte.setText("");
                    fakulte_getir();
                    pst.close();
                }
                rs.close();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Fakülte Eklenemedi ! -> Fakülte Adı Alanı Boş Bırakılamaz ! ");
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }

    }//GEN-LAST:event_ekleActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed

          String eski_fakulte_adi = fakulte_guncelle.getSelectedItem().toString().trim();
        if(!eski_fakulte_adi.equals("Seç"))
        {
        try {

          
            String yeni_fakulte_adi = yeni_fakulte.getText().trim();
            int tur_id = -1;

            String sql;

            sql = "select * from fakulteler where fakulte_adi='" +yeni_fakulte_adi+ "'";
            boolean kontrol_mevcutmu = false;
            // false'ü kitap tür olmadığını ifade ettiğini farz edelim.

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Bu Fakülte zaten mevcut ! , lütfen farklı bir Fakülte adı giriniz.");
                kontrol_mevcutmu = true;
            } else {
                kontrol_mevcutmu = false;
            }

            if (kontrol_mevcutmu != true) {

                if (!(yeni_fakulte_adi.isBlank())) {

                    sql = "update fakulteler set fakulte_adi=? where fakulte_adi='" +eski_fakulte_adi+ "'";
                    pst = conn.prepareStatement(sql);

                    pst.setString(1, yeni_fakulte_adi);

                    int deger = JOptionPane.showConfirmDialog(null, "DİKKAT ! ->Fakülte adı güncellemesi ile birlikte\nFakülteye ait bölümler ve öğrenciler'de etkilenecektir.\nİşleme devam etmek istiyormusunuz ?");

                    if(deger==0)
                    {
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "FAKÜLTE ADI GÜNCELLENDİ !");
                        
                        yeni_fakulte.setText("");
                        fakulte_guncelle.setSelectedItem(0);
                    }
                    else
                    JOptionPane.showMessageDialog(null, "İŞLEM İPTAL EDİLDİ !");
                    pst.close();

                    fakulte_getir();
                } else {
                    JOptionPane.showMessageDialog(null, "Geçersiz bir format girişi veya Boş alan !");

                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI HATA !: " + e.getSQLState());
            e.printStackTrace();
        }
        }
        else
        {
        JOptionPane.showConfirmDialog(null,"Lütfen bir fakülte seçiniz !");
        }
    }//GEN-LAST:event_guncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fakulteislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fakulteislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fakulteislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fakulteislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fakulteislemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cikis;
    private javax.swing.JButton ekle;
    private javax.swing.JTextField fakulte;
    private javax.swing.JComboBox<String> fakulte_guncelle;
    private javax.swing.JComboBox<String> fakulte_sil;
    private javax.swing.JButton geri;
    private javax.swing.JButton guncelle;
    private javax.swing.JMenuItem hakkimizda;
    private javax.swing.JMenu hakkinda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sil;
    private javax.swing.JTextField yeni_fakulte;
    // End of variables declaration//GEN-END:variables
}
