

import java.awt.HeadlessException;
import javax.swing.*;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Osman Karadeniz
 */
public class Giris extends javax.swing.JFrame {

    /**
     * Creates new form Giris
     */
    public Giris() {
        initComponents();
        conn=javabaglanti.BaglantiDb();
    }
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullanici_adi = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        sifre_metin = new javax.swing.JLabel();
        kullanici_ad_metin = new javax.swing.JLabel();
        giris = new javax.swing.JButton();
        kayit = new javax.swing.JButton();
        sifre_kurtar = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fırat Üniversitesi Kütüphane Otomasyonu");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kullanici_adi.setToolTipText("");
        kullanici_adi.setActionCommand("<Not Set>");
        kullanici_adi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(kullanici_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 230, 30));
        getContentPane().add(sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 230, 30));

        sifre_metin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sifre_metin.setForeground(new java.awt.Color(255, 255, 255));
        sifre_metin.setText("Şifre               :");
        getContentPane().add(sifre_metin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 130, 30));

        kullanici_ad_metin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kullanici_ad_metin.setForeground(new java.awt.Color(255, 255, 255));
        kullanici_ad_metin.setText("Kullanıcı Adı :");
        getContentPane().add(kullanici_ad_metin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 140, 30));

        giris.setBackground(new java.awt.Color(255, 255, 255));
        giris.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        giris.setText("GİRİŞ");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });
        getContentPane().add(giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 110, 30));

        kayit.setBackground(new java.awt.Color(255, 255, 255));
        kayit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kayit.setText("KAYIT");
        kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitActionPerformed(evt);
            }
        });
        getContentPane().add(kayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 90, 30));

        sifre_kurtar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sifre_kurtar.setForeground(new java.awt.Color(255, 255, 255));
        sifre_kurtar.setText("Şifrenizi mi unuttunuz?");
        sifre_kurtar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifre_kurtarMouseClicked(evt);
            }
        });
        getContentPane().add(sifre_kurtar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 160, 20));

        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/giris.png"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        arkaplan.getAccessibleContext().setAccessibleDescription("");

        jMenu5.setText("Sistem");
        jMenu5.setAutoscrolls(true);
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu5.setInheritsPopupMenu(true);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/bilgi.png"))); // NOI18N
        jMenuItem5.setText("Proje Hakkında");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/cikis.png"))); // NOI18N
        jMenuItem6.setText("Otomasyonu Kapat");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar3.add(jMenu5);

        setJMenuBar(jMenuBar3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitActionPerformed
setVisible(false);
Kayit kayitform = new Kayit();
kayitform.setVisible(true);
    }//GEN-LAST:event_kayitActionPerformed

    private void sifre_kurtarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifre_kurtarMouseClicked
       setVisible(false);
       Sifreyenile sifreyenileform=new Sifreyenile();
       sifreyenileform.setVisible(true);
    }//GEN-LAST:event_sifre_kurtarMouseClicked

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed
            
            String sql="select * from gorevli_hesaplar where hesap_kullanici_adi=? and hesap_sifre=?";
            String kulad = kullanici_adi.getText();
            String anahtar = sifre.getText();
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1,kulad);
                pst.setString(2,anahtar);
                rs=pst.executeQuery();
                        
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Giriş Başarılı");
                     rs.close();
                     pst.close();
                     
                     setVisible(false);
                     Anasayfa anasayfaform= new Anasayfa();
                     anasayfaform.setVisible(true);
                     
                } else{
                JOptionPane.showMessageDialog(null,"Giriş Başarısız");
                }
            }catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null,"VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
            } 
            
            
    }//GEN-LAST:event_girisActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break; }
          
             
             // UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel"); 

              
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton giris;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JButton kayit;
    private javax.swing.JLabel kullanici_ad_metin;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JLabel sifre_kurtar;
    private javax.swing.JLabel sifre_metin;
    // End of variables declaration//GEN-END:variables
}
