/**
 *
 * @author Osman Karadeniz
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class Kayit extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;

    /**
     * Creates new form Kayit
     */
    public Kayit() {
        super("Giris");
        initComponents();
        conn=javabaglanti.BaglantiDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ad_soyad = new javax.swing.JTextField();
        kullanici_adi = new javax.swing.JTextField();
        sifre = new javax.swing.JTextField();
        cevap = new javax.swing.JTextField();
        gvnlk_sorusu = new javax.swing.JComboBox<>();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fırat Üniversitesi Kütüpahane Otomasyonu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(155, 30, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/yenihesap.png"))); // NOI18N
        jLabel1.setText(" Hesap Oluşturma");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 390, 120));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<< Geri Dön");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Adınız Soyadınız  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kullanıcı Adı       :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Şifre                 :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Güvenlik Sorusu  : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cevap               :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OLUŞTUR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 280, 40));
        getContentPane().add(ad_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 230, 30));
        getContentPane().add(kullanici_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 230, 30));
        getContentPane().add(sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 230, 30));
        getContentPane().add(cevap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 230, 30));

        gvnlk_sorusu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bir Soru Seçiniz", "Telefon numaranızın son 3 hanesi kaçtır ?", "Takma adınız nedir ?", "En sevdiğiniz arkadaşınız kimdir ?", "En sevdiğiniz yemek hangisidir?", "Doğum yeriniz ?" }));
        gvnlk_sorusu.setToolTipText("");
        getContentPane().add(gvnlk_sorusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 280, 30));

        jMenu5.setText("Sistem");
        jMenu5.setAutoscrolls(true);
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu5.setInheritsPopupMenu(true);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/bilgi.png"))); // NOI18N
        jMenuItem5.setText("Proje Hakkında");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/cikis.png"))); // NOI18N
        jMenuItem6.setText("Otomasyonu Kapat");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar3.add(jMenu5);

        setJMenuBar(jMenuBar3);

        setSize(new java.awt.Dimension(501, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //KAYIT BUTON
        
        try{
  
  String adsoyad = ad_soyad.getText().trim();
  String kulad = kullanici_adi.getText().trim();
  String anahtar = sifre.getText().trim();
  String gvnlk = (String) gvnlk_sorusu.getSelectedItem();
  String cevapp = cevap.getText().trim();
          
  String sql ="insert into gorevli_hesaplar (hesap_ad_soyad,hesap_kullanici_adi,hesap_sifre,hesap_guvenlik_soru,hesap_guvenlik_cevap) values (?,?,?,?,?)";
  String sql1 = "select * from gorevli_hesaplar where hesap_kullanici_adi='"+kulad+"'";
  
  if(!(adsoyad.isBlank()|| kulad.isBlank() || anahtar.isBlank() || gvnlk.equals("Bir Soru Seçiniz") || cevapp.isBlank()))
          {
   pst=conn.prepareStatement(sql1);
   rs=pst.executeQuery();
   
   if(rs.next())
   {
       JOptionPane.showMessageDialog(null, "Hesap Oluşturulamadı ! -> Kullanıcı Adı Mevcut !");
   }
   else
   {
   pst = conn.prepareStatement(sql);
   pst.setString(1,adsoyad);
   pst.setString(2,kulad);
   pst.setString(3,anahtar);
   pst.setString(4,gvnlk);
   pst.setString(5,cevapp);
   pst.execute();
   JOptionPane.showMessageDialog(null, "Hesap Oluşturma İşlemi Başarılı !");
   pst.close();
        }
   rs.close();     
          }
  else
  {
   JOptionPane.showMessageDialog(null, "Hesap Oluşturulamadı ! -> Eksik Seçim veya Boş Alan");
  }
   }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //Geri Buton
       setVisible(false);
       new Giris().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_soyad;
    private javax.swing.JTextField cevap;
    private javax.swing.JComboBox<String> gvnlk_sorusu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JTextField sifre;
    // End of variables declaration//GEN-END:variables
}
