
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;

/**
 *
 * @author Osman Karadeniz
 */
public class KitapCikis extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form KitapCikis
     */

    public KitapCikis() {
        initComponents();
        conn = javabaglanti.BaglantiDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();
        cikis_tarih = new com.toedter.calendar.JDateChooser();
        islemi_tamamla = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        kitap_durum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ogrenci_ara = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ogrenci_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        temizle = new javax.swing.JButton();
        kitap_isbn = new javax.swing.JTextField();
        kitap_id = new javax.swing.JTextField();
        kitap_baslik = new javax.swing.JTextField();
        kitap_yazar = new javax.swing.JTextField();
        kitap_tur = new javax.swing.JTextField();
        kitap_isbn_2 = new javax.swing.JTextField();
        kitap_baski_sayi = new javax.swing.JTextField();
        kitap_baski_yil = new javax.swing.JTextField();
        kitap_yayinevi = new javax.swing.JTextField();
        kitap_sayfa_sayi = new javax.swing.JTextField();
        kitap_ara = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        kitap_fiyat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ogrenci_id = new javax.swing.JTextField();
        ogrenci_ad_soyad = new javax.swing.JTextField();
        ogrenci_no_2 = new javax.swing.JTextField();
        ogrenci_bolum = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        hakkinda = new javax.swing.JMenuItem();
        cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fırat Üniversitesi Kütüphane Otomasyonu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(155, 30, 72));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("KİTAP ÖDÜNÇ VERME İŞLEMİ");

        geri.setBackground(new java.awt.Color(255, 255, 255));
        geri.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        geri.setText("<< Geri Dön");
        geri.setFocusable(false);
        geri.setPreferredSize(new java.awt.Dimension(105, 25));
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        cikis_tarih.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(cikis_tarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 240, 30));

        islemi_tamamla.setBackground(new java.awt.Color(255, 255, 255));
        islemi_tamamla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        islemi_tamamla.setText("ÖDÜNÇ VER / İŞLEMİ TAMAMLA");
        islemi_tamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islemi_tamamlaActionPerformed(evt);
            }
        });
        getContentPane().add(islemi_tamamla, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 370, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Öğrenci Bilgileri");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 190, 30));

        kitap_durum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kitap_durum.setEnabled(false);
        kitap_durum.setFocusable(false);
        getContentPane().add(kitap_durum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Baskı Yılı :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        ogrenci_ara.setBackground(new java.awt.Color(255, 255, 255));
        ogrenci_ara.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ogrenci_ara.setText("Öğrenci Ara");
        ogrenci_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenci_araActionPerformed(evt);
            }
        });
        getContentPane().add(ogrenci_ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Kitap Bilgileri");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, 30));
        getContentPane().add(ogrenci_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 240, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kitap ISBN :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kitap ID :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Ödünç Verme Tarihi ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Yazar :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tür :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ISBN :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("KİTAP MEVCUTMU ? :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 140, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Baski Sayi :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Yayınevi :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Sayfa Sayısı :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Fiyat :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 30));

        temizle.setText("TEMİZLE");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });
        getContentPane().add(temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 90, 50));

        kitap_isbn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(kitap_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 240, 30));

        kitap_id.setEnabled(false);
        kitap_id.setFocusable(false);
        getContentPane().add(kitap_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 240, 30));

        kitap_baslik.setEnabled(false);
        kitap_baslik.setFocusable(false);
        getContentPane().add(kitap_baslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 240, 30));

        kitap_yazar.setEnabled(false);
        kitap_yazar.setFocusable(false);
        getContentPane().add(kitap_yazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 240, 30));

        kitap_tur.setEnabled(false);
        kitap_tur.setFocusable(false);
        getContentPane().add(kitap_tur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 240, 30));

        kitap_isbn_2.setEnabled(false);
        kitap_isbn_2.setFocusable(false);
        getContentPane().add(kitap_isbn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 240, 30));

        kitap_baski_sayi.setEnabled(false);
        kitap_baski_sayi.setFocusable(false);
        getContentPane().add(kitap_baski_sayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 240, 30));

        kitap_baski_yil.setEnabled(false);
        kitap_baski_yil.setFocusable(false);
        getContentPane().add(kitap_baski_yil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 240, 30));

        kitap_yayinevi.setEnabled(false);
        kitap_yayinevi.setFocusable(false);
        getContentPane().add(kitap_yayinevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 240, 30));

        kitap_sayfa_sayi.setEnabled(false);
        kitap_sayfa_sayi.setFocusable(false);
        getContentPane().add(kitap_sayfa_sayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 240, 30));

        kitap_ara.setBackground(new java.awt.Color(255, 255, 255));
        kitap_ara.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kitap_ara.setText("Kitap Ara");
        kitap_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_araActionPerformed(evt);
            }
        });
        getContentPane().add(kitap_ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 100, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Başlık :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 50, 30));

        kitap_fiyat.setEnabled(false);
        kitap_fiyat.setFocusable(false);
        getContentPane().add(kitap_fiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 240, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Öğrenci NO :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 80, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("No :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Bölüm :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 60, 30));

        ogrenci_id.setEnabled(false);
        ogrenci_id.setFocusable(false);
        getContentPane().add(ogrenci_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 240, 30));

        ogrenci_ad_soyad.setEnabled(false);
        ogrenci_ad_soyad.setFocusable(false);
        getContentPane().add(ogrenci_ad_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 240, 30));

        ogrenci_no_2.setEnabled(false);
        ogrenci_no_2.setFocusable(false);
        getContentPane().add(ogrenci_no_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 240, 30));

        ogrenci_bolum.setEnabled(false);
        ogrenci_bolum.setFocusable(false);
        getContentPane().add(ogrenci_bolum, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 240, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Ad - Soyad :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 80, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Öğrenci ID :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 80, 30));

        jMenu3.setText("Sistem");
        jMenu3.setAutoscrolls(true);
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu3.setInheritsPopupMenu(true);

        hakkinda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/bilgi.png"))); // NOI18N
        hakkinda.setText("Proje Hakkında");
        hakkinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakkindaActionPerformed(evt);
            }
        });
        jMenu3.add(hakkinda);

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/cikis.png"))); // NOI18N
        cikis.setText("Çıkış Yap");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        jMenu3.add(cikis);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(950, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hakkindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakkindaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hakkindaActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        setVisible(false);
        new Giris().setVisible(true);
    }//GEN-LAST:event_cikisActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        setVisible(false);
        new Anasayfa().setVisible(true);
    }//GEN-LAST:event_geriActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
      kitaplar_temizle();
      ogrenciler_temizle();
      kitaplar_on_off(false);
      ogrenciler_on_off(false);
      kitap_isbn.setText("");
      ogrenci_no.setText("");
      cikis_tarih.setCalendar(null);
    }//GEN-LAST:event_temizleActionPerformed

    void kitaplar_temizle()
    {
        kitap_id.setText("");
        kitap_baslik.setText("");
        kitap_yazar.setText("");
        kitap_isbn_2.setText("");
        kitap_baski_sayi.setText("");
        kitap_baski_yil.setText("");
        kitap_yayinevi.setText("");
        kitap_sayfa_sayi.setText("");
        kitap_fiyat.setText("");
        kitap_durum.setText("");
        kitap_tur.setText("");
    }
    
    void kitaplar_on_off(boolean durum) {

        if (durum) {
            kitap_baski_sayi.setEnabled(true);
            kitap_baski_yil.setEnabled(true);
            kitap_baslik.setEnabled(true);
            kitap_durum.setEnabled(true);
            kitap_fiyat.setEnabled(true);
            kitap_id.setEnabled(true);
            kitap_isbn_2.setEnabled(true);
            kitap_sayfa_sayi.setEnabled(true);
            kitap_tur.setEnabled(true);
            kitap_yayinevi.setEnabled(true);
            kitap_yazar.setEnabled(true);
        } else {
            kitaplar_temizle();
            
            kitap_baski_sayi.setEnabled(false);
            kitap_baski_yil.setEnabled(false);
            kitap_baslik.setEnabled(false);
            kitap_durum.setEnabled(false);
            kitap_fiyat.setEnabled(false);
            kitap_id.setEnabled(false);
            kitap_isbn_2.setEnabled(false);
            kitap_sayfa_sayi.setEnabled(false);
            kitap_tur.setEnabled(false);
            kitap_yayinevi.setEnabled(false);
            kitap_yazar.setEnabled(false);
        }

    }

    private void kitap_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_araActionPerformed

        String kitap_isbn_ = kitap_isbn.getText();

        try {
            String sql = "SELECT * from kitaplar where kitap_isbn=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, kitap_isbn_);
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Kitap Bulundu !");
                kitaplar_on_off(true);

                kitap_id.setText(rs.getString("kitap_id"));
                kitap_baslik.setText(rs.getString("kitap_baslik"));
                kitap_yazar.setText(rs.getString("kitap_yazar"));

                kitap_isbn_2.setText(rs.getString("kitap_isbn"));
                kitap_baski_sayi.setText(rs.getString("kitap_baski_sayi"));
                kitap_baski_yil.setText(rs.getString("kitap_baski_yil"));
                kitap_yayinevi.setText(rs.getString("kitap_yayinevi"));
                kitap_sayfa_sayi.setText(rs.getString("kitap_sayfa_sayi"));
                kitap_fiyat.setText(rs.getString("kitap_fiyat"));

                if (rs.getString("kitap_mevcutmu").equals("1"))
             {
                    kitap_durum.setForeground(Color.GREEN);
                    kitap_durum.setText("EVET");
                } else {
                    kitap_durum.setForeground(Color.red);
                    kitap_durum.setText("HAYIR");

                }
                
                String sql2 = "SELECT kitap_tur from kitap_turleri where kitap_turleri_id=?";
                pst = conn.prepareStatement(sql2);
                pst.setString(1, rs.getString("kitap_turleri_id"));
                rs = pst.executeQuery();
                
                if (rs.next()) {
                    kitap_tur.setText(rs.getString("kitap_tur"));
                }
               
                pst.close();
                rs.close();
               

            } else {
                JOptionPane.showMessageDialog(null, "Kitap Bulunamadı !");
                kitaplar_on_off(false);
                kitaplar_temizle();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }


    }//GEN-LAST:event_kitap_araActionPerformed

    void ogrenciler_on_off(boolean durum)
    {
        
        if(durum)
        {
        ogrenci_id.setEnabled(true);
        ogrenci_ad_soyad.setEnabled(true);
        ogrenci_no_2.setEnabled(true);
        ogrenci_bolum.setEnabled(true);
        }   
        else
        {
        ogrenci_id.setEnabled(false);
        ogrenci_ad_soyad.setEnabled(false);
        ogrenci_no_2.setEnabled(false);
        ogrenci_bolum.setEnabled(false);
        }
    
    }
    void ogrenciler_temizle()
    {
     ogrenci_id.setText("");
        ogrenci_ad_soyad.setText("");
        ogrenci_no_2.setText("");
        ogrenci_bolum.setText("");
    } 
    
    private void ogrenci_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenci_araActionPerformed
           
        String ogrenci_no_ = ogrenci_no.getText();

        try {
            String sql = "SELECT * from ogrenciler where ogrenci_no=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, ogrenci_no_);
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Öğrenci Bulundu !");
                ogrenciler_on_off(true);

                ogrenci_id.setText(rs.getString("ogrenci_id"));
                ogrenci_ad_soyad.setText(rs.getString("ogrenci_ad_soyad"));
                ogrenci_no_2.setText(rs.getString("ogrenci_no"));

                String sql2 = "SELECT bolum_adi from bolumler where bolum_id=?";
                pst = conn.prepareStatement(sql2);
                pst.setString(1, rs.getString("bolum_id"));
                rs = pst.executeQuery();
                
                if (rs.next()) {
                    ogrenci_bolum.setText(rs.getString("bolum_adi"));
                }
               
                pst.close();
                rs.close();
               

            } else {
                JOptionPane.showMessageDialog(null, "Öğrenci Bulunamadı !");
                ogrenciler_on_off(false);
                ogrenciler_temizle();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
        
    }//GEN-LAST:event_ogrenci_araActionPerformed

    private void islemi_tamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islemi_tamamlaActionPerformed
      
        String kitap_isbn_ = kitap_isbn_2.getText();
        String ogrenci_no_ = ogrenci_no_2.getText();
        String kitap_durum_ = kitap_durum.getText();
      
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       
        System.out.println(kitap_durum_);
        System.out.println(ogrenci_no_);
        System.out.println(kitap_isbn_);
        try
        {
            if ( !(kitap_isbn_.isBlank() || ogrenci_no_.isBlank())) {
                
                   String tarih = sdf.format(cikis_tarih.getDate());

                    if (kitap_durum_.equals("EVET")) {
                        System.out.println(kitap_durum_ + "GİRDİ !!");
                        String sql = "insert into islemler(islem_tip,ogrenci_no,kitap_isbn,tarih,odenen_ceza) values (odunc,?,?,?,0)";
                        pst = conn.prepareStatement(sql);
                        pst.setString(0, ogrenci_no_);
                        pst.setString(1, kitap_isbn_);
                       // pst.setString(2, cikis_tarih.getDateEditor().getUiComponent().getTe);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Ödünç Verme İşlemi Başarılı");
                        pst.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "Kitap Mevcut Değildir ! (İşlem Başarısız)...");
                    }
                }
            else {
                JOptionPane.showMessageDialog(null, "Öğrenci , Kitap , Tarih Bilgilerinde Eksik veya Hatalı giriş !");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }

    }//GEN-LAST:event_islemi_tamamlaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapCikis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cikis;
    private com.toedter.calendar.JDateChooser cikis_tarih;
    private javax.swing.JButton geri;
    private javax.swing.JMenuItem hakkinda;
    private javax.swing.JButton islemi_tamamla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kitap_ara;
    private javax.swing.JTextField kitap_baski_sayi;
    private javax.swing.JTextField kitap_baski_yil;
    private javax.swing.JTextField kitap_baslik;
    private javax.swing.JTextField kitap_durum;
    private javax.swing.JTextField kitap_fiyat;
    private javax.swing.JTextField kitap_id;
    private javax.swing.JTextField kitap_isbn;
    private javax.swing.JTextField kitap_isbn_2;
    private javax.swing.JTextField kitap_sayfa_sayi;
    private javax.swing.JTextField kitap_tur;
    private javax.swing.JTextField kitap_yayinevi;
    private javax.swing.JTextField kitap_yazar;
    private javax.swing.JTextField ogrenci_ad_soyad;
    private javax.swing.JButton ogrenci_ara;
    private javax.swing.JTextField ogrenci_bolum;
    private javax.swing.JTextField ogrenci_id;
    private javax.swing.JTextField ogrenci_no;
    private javax.swing.JTextField ogrenci_no_2;
    private javax.swing.JButton temizle;
    // End of variables declaration//GEN-END:variables
}
