/**
 *
 * @author Osman Karadeniz
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;

public class Kitapislemleri extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form kitapislemleri
     */
    public Kitapislemleri() {
        initComponents();
        conn = javabaglanti.BaglantiDb();
        tablo_veri_doldur();
        kitap_turleri_getir();
    }

    static int secilen_kitap_id;

    public void tablo_veri_doldur() {

        veritable.setDefaultEditor(Object.class, null);

        try {
         String sql = "SELECT kitap_id as '#ID' ,kitap_baslik as 'Başlık' ,kitap_yazar as 'Yazar' ,kitap_tur as 'Tür' ,kitap_isbn as 'ISBN' ,kitap_baski_sayi as 'Baskı Sayısı',kitap_baski_yil 'Baskı Yılı',kitap_yayinevi as 'Yayınevi',kitap_sayfa_sayi as 'Sayfa Sayısı',kitap_fiyat as 'Fiyat(TL)' from kitaplar AS kitap_turleri INNER JOIN kitap_turleri AS kitaplar on kitaplar.kitap_turleri_id=kitap_turleri.kitap_turleri_id";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            veritable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }

    }

//    public void tablo_baslik_guncelle()
//    { 
//    
//    veritable.getColumnModel().getColumn(0).setHeaderValue("#ID");
//    veritable.getColumnModel().getColumn(1).setHeaderValue("Başlık");
//    veritable.getColumnModel().getColumn(2).setHeaderValue("Yazar");
//    veritable.getColumnModel().getColumn(3).setHeaderValue("Tür");
//    veritable.getColumnModel().getColumn(4).setHeaderValue("ISBN");
//    veritable.getColumnModel().getColumn(5).setHeaderValue("Baskı Sayısı");
//    veritable.getColumnModel().getColumn(6).setHeaderValue("Baskı Yılı");
//    veritable.getColumnModel().getColumn(7).setHeaderValue("Yayınevi");
//    veritable.getColumnModel().getColumn(8).setHeaderValue("Sayfa Sayısı");
//    veritable.getColumnModel().getColumn(9).setHeaderValue("Fiyat");
//    
//    TableColumn col = veritable.getColumnModel().getColumn(10);
//    veritable.removeColumn(col);
//
// Yukardaki kodları tablo üzerinde başlık güncellemeleri için kullandım daha sonra sql kodları ile bunları yapabildiğimi hatırladım
// böylece bu fonksiyonu iptal ettim.
//    }
    
    void kitap_turleri_getir() {
        tur_bul.removeAllItems();
        yeni_tur.removeAllItems();

        tur_bul.addItem("Seç");
        yeni_tur.addItem("Seç");

        tur_bul.setSelectedIndex(0);
        yeni_tur.setSelectedIndex(0);

        try {

            String sql = "select kitap_tur from kitap_turleri";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                tur_bul.addItem(rs.getString("kitap_tur"));
                yeni_tur.addItem(rs.getString("kitap_tur"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        veritable = new javax.swing.JTable();
        filtrereset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        isbn_bul = new javax.swing.JTextField();
        baslik_bul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tur_bul = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yeni_baslik = new javax.swing.JTextField();
        yeni_yazar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        yeni_baskiyil = new javax.swing.JTextField();
        yeni_isbn = new javax.swing.JTextField();
        yeni_baskisayi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        yeni_fiyat = new javax.swing.JTextField();
        yeni_yayinevi = new javax.swing.JTextField();
        yeni_sayfasayi = new javax.swing.JTextField();
        yeni_tur = new javax.swing.JComboBox<>();
        sil = new javax.swing.JButton();
        temizle = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        kitap_id = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        hakkinda = new javax.swing.JMenuItem();
        cikis = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        kitapturislemleri = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        ogrenciekle = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fırat Üniversitesi Kütüphane Otomasyonu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(155, 30, 72));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("KİTAP (BUL / SİL / GÜNCELLE)");

        geri.setBackground(new java.awt.Color(255, 255, 255));
        geri.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        geri.setText("<< Geri Dön");
        geri.setFocusable(false);
        geri.setPreferredSize(new java.awt.Dimension(105, 25));
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        jScrollPane1.setEnabled(false);

        veritable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        veritable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        veritable.setToolTipText("");
        veritable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        veritable.setEditingColumn(0);
        veritable.setName("veritablosu"); // NOI18N
        veritable.setRequestFocusEnabled(false);
        veritable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        veritable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        veritable.setShowGrid(false);
        veritable.getTableHeader().setReorderingAllowed(false);
        veritable.setUpdateSelectionOnSort(false);
        veritable.setVerifyInputWhenFocusTarget(false);
        veritable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                veritableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(veritable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 240));

        filtrereset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        filtrereset.setText("Filtreyi Temizle");
        filtrereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtreresetActionPerformed(evt);
            }
        });
        getContentPane().add(filtrereset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 120, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GELİŞMİŞ FİLTRELEME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(155, 30, 72))); // NOI18N

        isbn_bul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isbn_bulKeyReleased(evt);
            }
        });

        baslik_bul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                baslik_bulKeyReleased(evt);
            }
        });

        jLabel3.setText("ISBN :");

        jLabel4.setText("Başlık :");

        tur_bul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seç" }));
        tur_bul.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tur_bulPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setText("Tür :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baslik_bul, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isbn_bul, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tur_bul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baslik_bul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbn_bul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tur_bul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 520, -1));

        jLabel5.setText("Tür :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 50, 30));

        jLabel6.setText("Başlık :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 60, 30));

        jLabel7.setText("Yazar :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 60, 30));

        yeni_baslik.setEnabled(false);
        getContentPane().add(yeni_baslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 150, 30));

        yeni_yazar.setEnabled(false);
        getContentPane().add(yeni_yazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 150, 30));

        jLabel8.setText("Baskı Yılı :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 80, 30));

        jLabel9.setText("ISBN :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 60, 30));

        jLabel10.setText("Baskı Sayı :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 70, 30));

        yeni_baskiyil.setEnabled(false);
        getContentPane().add(yeni_baskiyil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 150, 30));

        yeni_isbn.setEnabled(false);
        getContentPane().add(yeni_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 150, 30));

        yeni_baskisayi.setEnabled(false);
        getContentPane().add(yeni_baskisayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 150, 30));

        jLabel11.setText("Fiyat :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 60, 30));

        jLabel12.setText("Yayınevi :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 70, 30));

        jLabel13.setText("Sayfa Sayısı :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 110, 30));

        yeni_fiyat.setEnabled(false);
        getContentPane().add(yeni_fiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 150, 30));

        yeni_yayinevi.setEnabled(false);
        getContentPane().add(yeni_yayinevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 150, 30));

        yeni_sayfasayi.setEnabled(false);
        getContentPane().add(yeni_sayfasayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 150, 30));

        yeni_tur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seç" }));
        yeni_tur.setEnabled(false);
        getContentPane().add(yeni_tur, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 150, 30));

        sil.setText("SİL");
        sil.setEnabled(false);
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        getContentPane().add(sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 130, 50));

        temizle.setText("TEMİZLE");
        temizle.setEnabled(false);
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });
        getContentPane().add(temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 130, 50));

        guncelle.setText("GÜNCELLE");
        guncelle.setEnabled(false);
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 130, 50));

        kitap_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kitap_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(kitap_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 800, 30));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setAlignmentY(1.0F);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu3.setText("Sistem");
        jMenu3.setAutoscrolls(true);
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu3.setInheritsPopupMenu(true);

        hakkinda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/bilgi.png"))); // NOI18N
        hakkinda.setText("Proje Hakkında");
        jMenu3.add(hakkinda);

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/cikis.png"))); // NOI18N
        cikis.setText("Çıkış Yap");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        jMenu3.add(cikis);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("|");
        jMenu5.setAutoscrolls(true);
        jMenu5.setEnabled(false);
        jMenu5.setFocusable(false);
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setInheritsPopupMenu(true);
        jMenu5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenu5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu5);

        kitapturislemleri.setText("KİTAP TÜRÜ İŞLEMLERİ");
        kitapturislemleri.setAutoscrolls(true);
        kitapturislemleri.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        kitapturislemleri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kitapturislemleri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kitapturislemleri.setInheritsPopupMenu(true);
        kitapturislemleri.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kitapturislemleri.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kitapturislemleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitapturislemleriMouseClicked(evt);
            }
        });
        jMenuBar1.add(kitapturislemleri);

        jMenu7.setText("|");
        jMenu7.setAutoscrolls(true);
        jMenu7.setEnabled(false);
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu7.setInheritsPopupMenu(true);
        jMenu7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenu7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu7);

        ogrenciekle.setText("+KİTAP EKLE");
        ogrenciekle.setAutoscrolls(true);
        ogrenciekle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ogrenciekle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ogrenciekle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ogrenciekle.setInheritsPopupMenu(true);
        ogrenciekle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ogrenciekle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ogrenciekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ogrenciekleMouseClicked(evt);
            }
        });
        jMenuBar1.add(ogrenciekle);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void baslik_bulKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_baslik_bulKeyReleased
        kitap_bul(baslik_bul.getText().trim(), isbn_bul.getText().trim(), (String) tur_bul.getSelectedItem());
        kitapbilgiler_temizle();
        kitap_id.setText("");
        kitapbilgiler_ackapa(false);
    }//GEN-LAST:event_baslik_bulKeyReleased

    private void isbn_bulKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbn_bulKeyReleased
        kitap_bul(baslik_bul.getText().trim(), isbn_bul.getText().trim(), (String) tur_bul.getSelectedItem());
        kitapbilgiler_temizle();
        kitap_id.setText("");
        kitapbilgiler_ackapa(false);
    }//GEN-LAST:event_isbn_bulKeyReleased

    private void tur_bulPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tur_bulPopupMenuWillBecomeInvisible
        kitap_bul(baslik_bul.getText().trim(), isbn_bul.getText().trim(), (String) tur_bul.getSelectedItem());
        kitapbilgiler_temizle();
        kitap_id.setText("");
        kitapbilgiler_ackapa(false);
    }//GEN-LAST:event_tur_bulPopupMenuWillBecomeInvisible

    void tazele() {
        tablo_veri_doldur();
        kitap_turleri_getir();
        baslik_bul.setText("");
        isbn_bul.setText("");
        kitapbilgiler_temizle();
        kitap_id.setText("");
        kitapbilgiler_ackapa(false);
    }

    private void filtreresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtreresetActionPerformed
        tazele();
    }//GEN-LAST:event_filtreresetActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        setVisible(false);
        new Anasayfa().setVisible(true);
    }//GEN-LAST:event_geriActionPerformed

    void kitapbilgiler_ackapa(boolean kontrol) {
        if (kontrol == true) {
            yeni_baslik.setEnabled(true);
            yeni_yazar.setEnabled(true);
            yeni_baskisayi.setEnabled(true);
            yeni_baskiyil.setEnabled(true);
            yeni_fiyat.setEnabled(true);
            yeni_isbn.setEnabled(true);
            yeni_sayfasayi.setEnabled(true);
            yeni_tur.setEnabled(true);
            yeni_yayinevi.setEnabled(true);
            temizle.setEnabled(true);
            guncelle.setEnabled(true);
            sil.setEnabled(true);
        } else {
            yeni_baslik.setEnabled(false);
            yeni_yazar.setEnabled(false);
            yeni_baskisayi.setEnabled(false);
            yeni_baskiyil.setEnabled(false);
            yeni_fiyat.setEnabled(false);
            yeni_isbn.setEnabled(false);
            yeni_sayfasayi.setEnabled(false);
            yeni_tur.setEnabled(false);
            yeni_yayinevi.setEnabled(false);
            temizle.setEnabled(false);
            guncelle.setEnabled(false);
            sil.setEnabled(false);
        }

    }

    void kitapbilgiler_temizle() {
        yeni_baslik.setText("");
        yeni_yazar.setText("");
        yeni_baskisayi.setText("");
        yeni_baskiyil.setText("");
        yeni_fiyat.setText("");
        yeni_isbn.setText("");
        yeni_sayfasayi.setText("");
        yeni_tur.setSelectedIndex(0);
        yeni_yayinevi.setText("");
    }

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
        kitapbilgiler_temizle();
    }//GEN-LAST:event_temizleActionPerformed


    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed

        try {

            String baslik = yeni_baslik.getText().trim();
            String yazar = yeni_yazar.getText().trim();
            String tur = (String) yeni_tur.getSelectedItem();
            int tur_id = -1;

            String sql;

            sql = "select * from kitap_turleri where kitap_tur='" + tur + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                tur_id = rs.getInt("kitap_turleri_id");
            }
            pst.close();
            rs.close();

            String isbn = yeni_isbn.getText().trim();

            sql = "select * from kitaplar where kitap_isbn='" + isbn + "' and kitap_id!='"+secilen_kitap_id+"'";
            boolean kontrol_mevcutmu = false;
            // false'ü kitap ısbn olmadığını ifade ettiğini farz edelim.

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Bu ISBN'de bir kitap zaten mevcut ! , lütfen ISBN kodunu kontrol ediniz...");
                kontrol_mevcutmu = true;
            } else {
                kontrol_mevcutmu = false;
            }

            String baski_sayi = (String) yeni_baskisayi.getText();
            String baski_yil = yeni_baskiyil.getText().trim();
            String yayinevi = yeni_yayinevi.getText().trim();
            String sayfa_sayi = yeni_sayfasayi.getText().trim();
            String fiyat = yeni_fiyat.getText().trim();

            boolean kontrol_1 = genelfonksiyonlar.int_sayimi(yeni_baskisayi.getText());
            boolean kontrol_2 = genelfonksiyonlar.int_sayimi(yeni_baskiyil.getText());
            boolean kontrol_3 = genelfonksiyonlar.int_sayimi(yeni_sayfasayi.getText());
            boolean kontrol_4 = genelfonksiyonlar.double_sayimi(yeni_fiyat.getText());

            if (kontrol_mevcutmu != true) {
                if (!(baslik.isBlank() || yazar.isBlank() || isbn.isBlank() || yayinevi.isBlank()) && (kontrol_1 && kontrol_2 && kontrol_3 && kontrol_4) == true && !(tur.equals("Seç"))) {
                    sql = "update kitaplar set kitap_baslik= ? , kitap_yazar=? , kitap_turleri_id=? , kitap_isbn=? , kitap_baski_sayi=?, kitap_baski_yil=? , kitap_yayinevi=? , kitap_sayfa_sayi=? , kitap_fiyat=? where kitap_id='" + secilen_kitap_id + "'";
                    pst = conn.prepareStatement(sql);

                    pst.setString(1, baslik);
                    pst.setString(2, yazar);
                    pst.setInt(3, tur_id);
                    pst.setString(4, isbn);
                    pst.setString(5, baski_sayi);
                    pst.setString(6, baski_yil);
                    pst.setString(7, yayinevi);
                    pst.setString(8, sayfa_sayi);
                    pst.setString(9, fiyat);
                    pst.executeUpdate();
                    pst.close();
                    JOptionPane.showMessageDialog(null, "KİTAP GÜNCELLENDİ !");
                    tablo_veri_doldur();
                } else {
                    JOptionPane.showMessageDialog(null, "Geçersiz bir format girişi veya Boş alan !");

                }
            } 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI HATA !: " + e.getSQLState());
            e.printStackTrace();
        }


    }//GEN-LAST:event_guncelleActionPerformed

    private void veritableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veritableMouseReleased

        DefaultTableModel model = (DefaultTableModel) veritable.getModel();

        int secilen_satir_indis = veritable.getSelectedRow();

        secilen_kitap_id = Integer.parseInt(model.getValueAt(secilen_satir_indis, 0).toString());
        String tur = model.getValueAt(secilen_satir_indis, 3).toString();

        kitap_id.setText("► SEÇİLEN KİTAP ID : " + secilen_kitap_id + " ◄");
        kitapbilgiler_ackapa(true);
        yeni_baslik.setText(model.getValueAt(secilen_satir_indis, 1).toString());
        yeni_yazar.setText(model.getValueAt(secilen_satir_indis, 2).toString());

        yeni_tur.setSelectedItem(tur);

        yeni_isbn.setText(model.getValueAt(secilen_satir_indis, 4).toString());
        yeni_baskisayi.setText(model.getValueAt(secilen_satir_indis, 5).toString());
        yeni_baskiyil.setText(model.getValueAt(secilen_satir_indis, 6).toString());
        yeni_yayinevi.setText(model.getValueAt(secilen_satir_indis, 7).toString());
        yeni_sayfasayi.setText(model.getValueAt(secilen_satir_indis, 8).toString());;
        yeni_fiyat.setText(model.getValueAt(secilen_satir_indis, 9).toString());


    }//GEN-LAST:event_veritableMouseReleased

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed

        try {
            String sql = "delete from kitaplar where kitap_id=" + secilen_kitap_id + ";";
            pst = conn.prepareStatement(sql);

            int deger = JOptionPane.showConfirmDialog(null, "İD : " + secilen_kitap_id + " olan kitabı silme işlemine devam etmek istiyor musunuz ?");

            if (deger == 0) {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "KİTAP SİLİNDİ !");
                tazele();
            } else {
                JOptionPane.showMessageDialog(null, "İŞLEM İPTAL EDİLDİ !");
            }

            pst.close();
            tablo_veri_doldur();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI HATA !: " + e.getSQLState());
        }

    }//GEN-LAST:event_silActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        setVisible(false);

        Giris girisform = new Giris();
        girisform.setVisible(true);
    }//GEN-LAST:event_cikisActionPerformed

    private void kitapturislemleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitapturislemleriMouseClicked
  setVisible(false);
        new Kitapturuislemleri().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_kitapturislemleriMouseClicked

    private void ogrenciekleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ogrenciekleMouseClicked
       setVisible(false);
        new Yenikitap().setVisible(true); 
    }//GEN-LAST:event_ogrenciekleMouseClicked

    void kitap_bul(String baslik, String isbn, String tur) {
        if (tur.equals("Seç")) {
            tur = "";
        }

        try {
//   String sql = "SELECT kitaplar.kitap_id as '#ID' ,kitaplar.kitap_baslik as 'Başlık' ,kitaplar.kitap_yazar as 'Yazar' ,kitap_turleri.kitap_tur as 'Tür' ,kitaplar.kitap_isbn as 'ISBN' ,kitaplar.kitap_baski_sayi as 'Baskı Sayısı',kitaplar.kitap_baski_yil 'Baskı Yılı',kitaplar.kitap_yayinevi as 'Yayınevi',kitaplar.kitap_sayfa_sayi as 'Sayfa Sayısı',kitaplar.kitap_fiyat as 'Fiyat' from kitaplar,kitap_turleri where kitap_baslik like '%"+baslik+"%' && kitap_isbn like '%"+isbn+"%' && kitap_turleri.kitap_tur like '%"+tur+"%'";
            String sql = "SELECT kitap_id as '#ID' ,kitap_baslik as 'Başlık' ,kitap_yazar as 'Yazar' ,kitap_tur as 'Tür' ,kitap_isbn as 'ISBN' ,kitap_baski_sayi as 'Baskı Sayısı',kitap_baski_yil 'Baskı Yılı',kitap_yayinevi as 'Yayınevi',kitap_sayfa_sayi as 'Sayfa Sayısı',kitap_fiyat as 'Fiyat(TL)' from kitaplar AS kitap_turleri INNER JOIN kitap_turleri AS kitaplar on kitaplar.kitap_turleri_id=kitap_turleri.kitap_turleri_id where kitap_baslik like '%" + baslik + "%' && kitap_isbn like '%" + isbn + "%' && kitap_tur like '%" + tur + "%'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            veritable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
        //tablo_baslik_guncelle();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitapislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitapislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitapislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitapislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitapislemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baslik_bul;
    private javax.swing.JMenuItem cikis;
    private javax.swing.JButton filtrereset;
    private javax.swing.JButton geri;
    private javax.swing.JButton guncelle;
    private javax.swing.JMenuItem hakkinda;
    private javax.swing.JTextField isbn_bul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kitap_id;
    private javax.swing.JMenu kitapturislemleri;
    private javax.swing.JMenu ogrenciekle;
    private javax.swing.JButton sil;
    private javax.swing.JButton temizle;
    private javax.swing.JComboBox<String> tur_bul;
    private javax.swing.JTable veritable;
    private javax.swing.JTextField yeni_baskisayi;
    private javax.swing.JTextField yeni_baskiyil;
    private javax.swing.JTextField yeni_baslik;
    private javax.swing.JTextField yeni_fiyat;
    private javax.swing.JTextField yeni_isbn;
    private javax.swing.JTextField yeni_sayfasayi;
    private javax.swing.JComboBox<String> yeni_tur;
    private javax.swing.JTextField yeni_yayinevi;
    private javax.swing.JTextField yeni_yazar;
    // End of variables declaration//GEN-END:variables
}
