
import com.mysql.cj.util.StringUtils;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Osman Karadeniz
 */
public class Sifreyenile extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form Sifreyenile
     */
    public Sifreyenile() {
       
        initComponents();
        conn=javabaglanti.BaglantiDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kullanici_adi = new javax.swing.JTextField();
        kullanici_ad_soyad = new javax.swing.JTextField();
        cevap = new javax.swing.JTextField();
        yeni_sifre = new javax.swing.JTextField();
        sifrereset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        sifre_metin = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        guvenlik_sorusu = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fırat Üniversitesi Kütüphane Otomasyonu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Kullanıcı adı :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("Ad Soyad :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Cevap :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 300, 60, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("Yeni Şifre : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 350, 90, 30));
        getContentPane().add(kullanici_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 210, 30));

        kullanici_ad_soyad.setEditable(false);
        kullanici_ad_soyad.setEnabled(false);
        getContentPane().add(kullanici_ad_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 260, 30));

        cevap.setEnabled(false);
        getContentPane().add(cevap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 260, 30));

        yeni_sifre.setEnabled(false);
        getContentPane().add(yeni_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 260, 30));

        sifrereset.setBackground(new java.awt.Color(255, 255, 255));
        sifrereset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sifrereset.setText("Şifre Yenile");
        sifrereset.setEnabled(false);
        sifrereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreresetActionPerformed(evt);
            }
        });
        getContentPane().add(sifrereset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 350, 50));

        jPanel1.setBackground(new java.awt.Color(155, 30, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sifre_metin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        sifre_metin.setForeground(new java.awt.Color(255, 255, 255));
        sifre_metin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/sifreyenile.png"))); // NOI18N
        sifre_metin.setText(" Şifre Yenileme");
        jPanel1.add(sifre_metin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 350, 110));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<< Geri Dön");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 110));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("Güvenlik Sorusu :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        guvenlik_sorusu.setEditable(false);
        guvenlik_sorusu.setEnabled(false);
        getContentPane().add(guvenlik_sorusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 260, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/ara.png"))); // NOI18N
        jButton3.setText("Bul");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, 60));

        jMenu5.setText("Sistem");
        jMenu5.setAutoscrolls(true);
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu5.setInheritsPopupMenu(true);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/bilgi.png"))); // NOI18N
        jMenuItem5.setText("Proje Hakkında");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/cikis.png"))); // NOI18N
        jMenuItem6.setText("Otomasyonu Kapat");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar3.add(jMenu5);

        setJMenuBar(jMenuBar3);

        setSize(new java.awt.Dimension(516, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void Temizle(){
     kullanici_ad_soyad.setText("");
     guvenlik_sorusu.setText("");
     cevap.setText("");
     yeni_sifre.setText("");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new Giris().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

     Temizle();
    //KULLANICI ADI BUL BUTONU
     String kullanici_ad = kullanici_adi.getText();
     String sql = "select * from gorevli_hesaplar where hesap_kullanici_adi='"+kullanici_ad+"'";
    
     try{
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         
     if(rs.next())
     {
     kullanici_ad_soyad.setText(rs.getString(2));
     guvenlik_sorusu.setText(rs.getString(5));
     rs.close();
     pst.close();
     kullanici_ad_soyad.setEnabled(true);
     guvenlik_sorusu.setEnabled(true);
     cevap.setEnabled(true);
     yeni_sifre.setEnabled(true);
     sifrereset.setEnabled(true);
        }
     else
     {
         JOptionPane.showMessageDialog(null, "Kullanıcı Bulunamadı");
         
         kullanici_ad_soyad.setEnabled(false);
         guvenlik_sorusu.setEnabled(false);
         cevap.setEnabled(false);
         yeni_sifre.setEnabled(false);
         sifrereset.setEnabled(false);
         
        Temizle();
        }
     
     
     }catch(SQLException e)
     {
        JOptionPane.showMessageDialog(null," VERİ TABANI BAĞLANTISI BAŞARISIZ !" + e.getSQLState());
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sifreresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreresetActionPerformed
       
        String kullanici_ad = kullanici_adi.getText();
        String sifre = yeni_sifre.getText().trim();
        String cevap_icerik = cevap.getText();
       
        
        try 
        {
        String sql1 = "select * from gorevli_hesaplar where hesap_kullanici_adi='"+kullanici_ad+"'";
        String sql2="update gorevli_hesaplar set hesap_sifre='"+sifre+"' where hesap_kullanici_adi='"+kullanici_ad+"'";
        
        pst=conn.prepareStatement(sql1);
        rs=pst.executeQuery();
        
            if(rs.next())
            {
                
            if(cevap_icerik.equals(rs.getString(6)))
            {
                if(!(StringUtils.isEmptyOrWhitespaceOnly(sifre)))
                {
                 pst = conn.prepareStatement(sql2);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Şifre Yineleme Başarılı !");
                rs.close();
                pst.close();
                }
                else
            {
            JOptionPane.showMessageDialog(null, "Şifre Yineleme Başarısız -> Yeni Şifre Alanını Doldurunuz !");
            }
              
            }
              else
            {
            JOptionPane.showMessageDialog(null, "Şifre Yenileme Başarısız -> Cevap Yanlış !");
            }
            
            }
          
        }
        catch(SQLException e)
        {
        JOptionPane.showMessageDialog(null,"VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
    }//GEN-LAST:event_sifreresetActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sifreyenile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sifreyenile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sifreyenile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sifreyenile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sifreyenile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cevap;
    private javax.swing.JTextField guvenlik_sorusu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kullanici_ad_soyad;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JLabel sifre_metin;
    private javax.swing.JButton sifrereset;
    private javax.swing.JTextField yeni_sifre;
    // End of variables declaration//GEN-END:variables
}
