
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Osman Karadeniz
 */
public class Yeniogrenci extends javax.swing.JFrame {
 Connection conn;
 ResultSet rs;
 PreparedStatement pst;
 
    /**
     * Creates new form Yeniogrenci
     */
    public Yeniogrenci() {
        initComponents();
        conn = javabaglanti.BaglantiDb();
        fakulte_getir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ad_soyad = new javax.swing.JTextField();
        ogrenci_no = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        geri = new javax.swing.JButton();
        kaydet = new javax.swing.JButton();
        fakulte = new javax.swing.JComboBox<>();
        temizle = new javax.swing.JButton();
        bolum = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fırat Üniversitesi Kütüphane Otomasyonu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ad - soyad :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Öğrenci no :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bölüm :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 60, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Fakülte :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 160, 60, 30));
        getContentPane().add(ad_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 220, 30));
        getContentPane().add(ogrenci_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 220, 30));

        jPanel1.setBackground(new java.awt.Color(155, 30, 72));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("YENİ ÖĞRENCİ EKLE");
        jLabel11.setToolTipText("");

        geri.setBackground(new java.awt.Color(255, 255, 255));
        geri.setText("<< Geri Dön");
        geri.setFocusable(false);
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(geri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(geri)
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        kaydet.setBackground(new java.awt.Color(255, 255, 255));
        kaydet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kaydet.setText("KAYDET");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });
        getContentPane().add(kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 310, 40));

        fakulte.setFocusable(false);
        fakulte.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                fakultePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(fakulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 220, 30));

        temizle.setBackground(new java.awt.Color(255, 255, 255));
        temizle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        temizle.setText("TEMİZLE");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });
        getContentPane().add(temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 40));

        bolum.setEnabled(false);
        bolum.setFocusable(false);
        getContentPane().add(bolum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 220, 30));

        jMenu3.setText("Sistem");
        jMenu3.setAutoscrolls(true);
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu3.setInheritsPopupMenu(true);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/bilgi.png"))); // NOI18N
        jMenuItem2.setText("Proje Hakkında");
        jMenu3.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/cikis.png"))); // NOI18N
        jMenuItem1.setText("Çıkış Yap");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(466, 362));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        setVisible(false);
        new Ogrenciislemleri().setVisible(true);
    }//GEN-LAST:event_geriActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed

        try{
            String adsoyad = ad_soyad.getText().trim();
            String ogrno = ogrenci_no.getText().trim();
            String secilen_fakulte =  (String) fakulte.getSelectedItem();
            String secilen_bolum =  (String) bolum.getSelectedItem();
            
          
                if (!(ogrno.isBlank() || adsoyad.isBlank()) && !( (secilen_fakulte.equals("Seç")) || (secilen_bolum.equals("Seç"))) )  
                {
           String sql1 = "select bolum_id from bolumler where bolum_adi='"+secilen_bolum+"' and fakulte_id in (select fakulte_id from fakulteler where fakulte_adi='"+secilen_fakulte+"')";
           int bolum_id =-1;
           
           pst=conn.prepareStatement(sql1);
           rs=pst.executeQuery();
           
           while(rs.next())
           {
           bolum_id=rs.getInt("bolum_id");
           }
           pst.close();
           rs.close();
            
            
            String sql2 ="insert into ogrenciler(ogrenci_no,ogrenci_ad_soyad,bolum_id) values (?,?,'"+bolum_id+"')";
            
            String sql3 = "select * from ogrenciler where ogrenci_no='"+ogrno+"'";
            boolean kontrol_mevcutmu=false;
            // false'ü öğrencinin olmadığı bilgisi olarak kabul ediyorum.
                    
                    
                    
                pst=conn.prepareStatement(sql3);
                rs=pst.executeQuery();

                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null, "Öğrenci Kaydı Başarısız ! -> Öğrenci No. Mevcut !");
                    kontrol_mevcutmu =true;
                }
                else
                { kontrol_mevcutmu =false; }
                
                if(kontrol_mevcutmu !=true )
                {
                    pst = conn.prepareStatement(sql2);
                    pst.setString(1,ogrno);
                    pst.setString(2,adsoyad);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Öğrenci Kayıt İşlemi Başarılı !");
                    pst.close();
                }
                rs.close();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Öğrenci Kaydı Başarısız ! -> Geçersiz bir değer girişi veya Boş Alan");
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }

    }//GEN-LAST:event_kaydetActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
        ad_soyad.setText("");
        ogrenci_no.setText("");
        fakulte.setSelectedIndex(0);
        bolum.setEnabled(false);
        bolum.removeAllItems();
    }//GEN-LAST:event_temizleActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);

        Giris girisform = new Giris();
        girisform.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    static String secilen;   
    private void fakultePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_fakultePopupMenuWillBecomeInvisible
       
        secilen = fakulte.getSelectedItem().toString();
        
        if(secilen.equals("Seç"))
        {
        bolum.setEnabled(false);
        bolum.removeAllItems();
        }
        else
        {
         bolum.setEnabled(true);
         bolum_getir(secilen);
         
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fakultePopupMenuWillBecomeInvisible
     
     void fakulte_getir() {
        
        fakulte.removeAllItems();
        fakulte.addItem("Seç");
        fakulte.setSelectedIndex(0);
        
        try {

            String sql = "select fakulte_adi from fakulteler";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                fakulte.addItem(rs.getString("fakulte_adi"));
            }
            pst.close();
            rs.close();
            

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
    }
     
    void bolum_getir(String fakulte_adi) {

        bolum.removeAllItems();

        bolum.addItem("Seç");

        bolum.setSelectedIndex(0);

        try {

            String sql = "select bolum_adi from bolumler where fakulte_id in (select fakulte_id from fakulteler where fakulte_adi='"+fakulte_adi+"')";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {

                bolum.addItem(rs.getString("bolum_adi"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "VERİ TABANI BAĞLANTISI BAŞARISIZ !: " + e.getSQLState());
        }
    }
   
    
    
    
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yeniogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yeniogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yeniogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yeniogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yeniogrenci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_soyad;
    private javax.swing.JComboBox<String> bolum;
    private javax.swing.JComboBox<String> fakulte;
    private javax.swing.JButton geri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kaydet;
    private javax.swing.JTextField ogrenci_no;
    private javax.swing.JButton temizle;
    // End of variables declaration//GEN-END:variables
}
